server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    username: postgres
    password: rootservgeevich
    url: jdbc:postgresql://localhost:5432/restservice
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
  security:
    password:
      strength: 12